Fixes policy CMP0135 warning in CMake 3.24
osrf/osrf_testing_tools_cpp pull request #71
Opened 2022-09-07 21:10 UTC by Crola1702

### Warning fix

Signed-off-by: Cristóbal Arroyo <cristobal.arroyo@ekumenlabs.com>

[This](https://cmake.org/cmake/help/latest/policy/CMP0135.html) warning started appearing on new machines ([windows-container-bd99e2f0](https://ci.ros2.org/computer/windows-container-bd99e2f0/) and [windows-container-9e2bca8d](https://ci.ros2.org/computer/windows-container-9e2bca8d/)). It’s caused by a new CMake version (3.24) that expects this policy to be set.

`osrf_testing_tools_cpp` it's the first package that shows this warning on [Windows Release](https://ci.ros2.org/view/nightly/job/nightly_win_rel/2419/) and [Windows Debug](https://ci.ros2.org/view/nightly/job/nightly_win_deb/2473/)

This PR sets CMP0135 policy by giving the option `DOWNLOAD_EXTRACT_TIMESTAMP FALSE` to `ExternalProject_Add` instruction

Replicating this problem: [![Build Status](https://ci.ros2.org/job/ci_windows/17703/badge/icon)](https://ci.ros2.org/job/ci_windows/17703/)

Solution with this PR changes:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17243)](http://ci.ros2.org/job/ci_linux/17243/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11784)](http://ci.ros2.org/job/ci_linux-aarch64/11784/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17704)](http://ci.ros2.org/job/ci_windows/17704/)

2022-09-07 21:18 UTC, clalancette commented
Unfortunately, it looks like DOWNLOAD_EXTRACT_TIMESTAMP is new in CMake 3.24, and so older CMake complains about it.  So with this change, we trade off one warning for another.

I think we're going to have to do something different here.  Either we'll have to set CMP0135 explicitly to OLD (hopefully older CMake will be OK with that), or we'll have to do some conditional code to figure out what version of CMake we are using and only add the timestamp if it is CMake >= 3.24.

2022-09-07 21:24 UTC, Crola1702 commented
> Either we'll have to set CMP0135 explicitly to OLD (hopefully older CMake will be OK with that), or we'll have to do some conditional code to figure out what version of CMake we are using and only add the timestamp if it is CMake >= 3.24.

Okay I was thinking on this solution:
```
if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.24")
    cmake_policy(SET CMP0135 NEW)
endif()
```

2022-09-07 21:36 UTC, Blast545 commented
@Crola1702 Shouldn't it be OLD in that case?

```
if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.24")
    cmake_policy(SET CMP0135 OLD)
endif()
``` 

Another option could be checking if the policy is available, re-using the pattern used here:

https://github.com/ros2/rviz/blob/1ee274d74b156390260910b042242a5c11a34c00/rviz_ogre_vendor/rviz_ogre_vendor-extras.cmake.in#L115-L117

2022-09-07 22:00 UTC, Crola1702 commented
> Another option could be checking if the policy is available, re-using the pattern used here:

I like that. I just committed that solution.

2022-09-08 12:42 UTC, clalancette requested changes
The concept looks good to me, thanks for this!

I left two nitpicks inline, to make the comment a little more verbose and to decrease the indentation (while we aren't totally consistent here, we generally use 2 spaces for indentation in CMakeLists.txt).

Once those are fixed and we've run CI again, this looks good to me!

2022-09-08 12:42 UTC, clalancette commented on osrf_testing_tools_cpp/vendor/google/googletest/googletest-external-project-add.cmake.in
> +endif()
```suggestion
# Avoid DOWNLOAD_EXTRACT_TIMESTAMP warning for CMake >= 3.24
if (POLICY CMP0135)
  cmake_policy(SET CMP0135 OLD)
endif()
```

2022-09-08 12:43 UTC, Crola1702 commented on osrf_testing_tools_cpp/vendor/google/googletest/googletest-external-project-add.cmake.in
> +endif()
Ohh didn't notice that. Thanks Chris

2022-09-08 12:44 UTC, clalancette approved these changes

2022-09-08 13:24 UTC, merged